name: hiperhealth
channels:
  - conda-forge
  - defaults

dependencies:
  - python >=3.10,<=3.13
  - pip
  - nodejs  # used by semantic-release
  - tesseract
  - libmagic
  - uv
  - pip:
      - paginate==0.5.6  # distlib issue
